# Generated by Django 5.1.1 on 2024-11-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_alter_voter_precinct_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="voter_id",
            field=models.CharField(max_length=50),
        ),
    ]
