# Generated by Django 5.1.1 on 2024-12-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_member_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
