# Generated by Django 5.1.1 on 2024-12-10 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_member_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="project.member",
            ),
        ),
    ]
