# Generated by Django 5.1.1 on 2024-12-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_checkin_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
