# Generated by Django 5.1.1 on 2024-12-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_member_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(default="None", max_length=15),
        ),
    ]
